name: go
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

jobs:
  unit:
    name: unit
    runs-on: ubuntu-20.04
    steps:
      - name: Install package
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: btrfs-progs libgpgme-dev
          version: 1.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out